name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
        # id permit put a name tu result that returns the actions semantic with format
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "New Version: $NEW_VERSION !!!!!!!!!!!!!"
    - name: Build Docker Image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker build -t yanstack15/docker-graphql:$NEW_VERSION .
        docker build -t yanstack15/docker-graphql:latest .
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}}    
      run: |
        docker push yanstack15/docker-graphql:$NEW_VERSION
        docker push yanstack15/docker-graphql:latest
        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
